config/routes.rb
EmealsWeb::Application.routes.draw do

  root 'meals#index'
  resources :meals do
    post   'upload', on: :collection
    patch  'rate', on: :member
    delete 'hide', on: :member
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  

end

app/models/concerns/meal_search.rb
module MealSearch
  extend ActiveSupport::Concern

  included do
    include Tire::Model::Search
    include Tire::Model::Callbacks

    mapping do
      indexes :id, index: :not_analyzed
      indexes :flags, as: Proc.new { flags.map(&:humanize) }
      indexes :entree_name, as: 'entree.name'
      indexes :side_name, as: 'side.name'
      indexes :entree_instructions, as: 'entree.instructions'
      indexes :side_instructions, as: 'side.instructions'
    end

    def self.search(query, page = nil)
      result_page = page || 1
      per_page = 20

      return visible.paginate(page: result_page, per_page: per_page) if query.blank?
      tire.search(query, load: {include: [:entree, :side]}, page: result_page, per_page: per_page)
    end
  end
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  #has_one :meal
  has_many :ingredients
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank

  def instructions_list
    return [] if instructions.blank?
    instructions.gsub("\r\n", "\n").gsub("\r", "\n").split("\n")
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  default_scope -> { order(:id) }

  belongs_to :dish

  Units = Emeals::Quantity::UNITS
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  include MealSearch

  default_scope -> { order('created_at DESC').includes(:entree, :side) }
  scope :visible, -> { where(hidden_at: nil) }

  validates :entree, :side, presence: true
  validates :rating, numericality: {less_than: 6, greater_than_or_equal_to: 0}

  belongs_to :entree, class_name: "Dish", autosave: true
  belongs_to :side,   class_name: "Dish", autosave: true

  Flags = Emeals::Meal::FLAGS

  def hide
    update hidden_at: Time.zone.now
  end
end

app/models/meal_form.rb
require 'form'
require 'time_converter'

class MealForm < Form
  attr_reader :meal

  attribute :entree, Dish
  attribute :side,   Dish
  attribute :flags,  Array[String]
  attribute :rating, Integer

  %w(prep cook total).each do |time|
    attribute :"#{time}_hours", Integer
    attribute :"#{time}_minutes", Integer
  end

  validates :rating, numericality: {less_than: 6, greater_than_or_equal_to: 0}

  accepts_nested_attributes_for :entree, :side

  def initialize(meal = Meal.new)
    @meal = meal
    self.entree = meal.entree
    self.side   = meal.side
    self.flags  = meal.flags
    self.rating = meal.rating

    self.prep_hours, self.prep_minutes   = split_time(meal.prep_time)
    self.cook_hours, self.cook_minutes   = split_time(meal.cook_time)
    self.total_hours, self.total_minutes = split_time(meal.total_time)
  end

  protected

  def persist!
    meal.flags  = flags
    meal.rating = rating
    %w(prep cook total).each do |time|
      meal[:"#{time}_time"] = join_time(send("#{time}_hours"), send("#{time}_minutes"))
    end
    meal.save
  end

  private

  def split_time(time_string)
    TimeConverter.new.split(time_string)
  end

  def join_time(hours, minutes)
    TimeConverter.new.join(hours, minutes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/meal_parameters.rb
module MealParameters
  def meal_params
    params.require(:meal).permit(permitted_meal_params)
  end

  def uploaded_menu
    params[:menu]
  end

  private

  def permitted_meal_params
    %w(
      rating id
      prep_hours prep_minutes
      cook_hours cook_minutes
      total_hours total_minutes
    ) + [{flags: [], entree_attributes: permitted_dish_params, side_attributes: permitted_dish_params}]
  end

  def permitted_dish_params
    [:name, :instructions, ingredients_attributes: permitted_ingredient_params]
  end

  def permitted_ingredient_params
    [:id, :amount, :unit, :description, :_destroy]
  end
end

app/controllers/concerns/view_data.rb
module ViewData
  extend ActiveSupport::Concern

  included do
    def self.data(method_name, &block)
      ivar = "@#{method_name}"
      define_method method_name do
        instance_variable_get(ivar) || instance_variable_set(ivar, instance_eval(&block))
      end
      helper_method method_name
      protected method_name
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  include MealParameters
  include ViewData

  data(:meal)      { Meal.find(params[:id]) }
  data(:meal_form) { MealForm.new(meal) }
  data(:meals)     { Meal.search(params[:q], params[:page]) }

  def index; end

  def show; end

  def edit; end

  def update
    meal_form.attributes = meal_params.to_hash
    meal_form.save

    redirect_to root_url
  end

  def destroy
    meal.destroy
    redirect_to root_url
  end

  def hide
    meal.hide
    redirect_to root_url
  end

  def upload
    ImportMenuService.new.import(uploaded_menu)
    redirect_to root_url
  end

  def rate
    meal.update rating: params[:rating]
    render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FoundationHelper

  def icon(klass)
    "<i class=\"foundicon-#{klass}\"></i>".html_safe
  end
end

app/helpers/foundation_helper.rb
module FoundationHelper
  class SectionBuilder
    attr_reader :slug, :options, :title_block, :content_block
    def initialize(slug, options = {})
      @slug = slug
      @options = options
    end

    def build
      yield self
      self
    end

    def title(options = {}, &block)
      @options[:title_class] = options[:class] if options[:class]
      @title_block = block
    end

    def content(options = {}, &block)
      @options[:content_class] = options[:class] if options[:class]
      @content_block = block
    end
  end

  def section(slug, options = {}, &block)
    builder = SectionBuilder.new(slug, options).build(&block)
    content_tag(:section, class: builder.options[:class]) do
      concat content_tag(:p, content_tag(:a, href: "##{builder.slug}", &builder.title_block),
                         :class => builder.options[:title_class], 'data-section-title' => "")
      concat content_tag(:div, :class => builder.options[:content_class],
                         'data-slug' => builder.slug, 'data-section-content' => '', &builder.content_block)
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
  class MealsFormBuilder < ActionView::Helpers::FormBuilder
    def unit_field(field = :unit, html_options = {})
      html_options[:class] = 'no-custom' if html_options[:disabled]
      select field, Ingredient::Units, {include_blank: true}, html_options
    end

    def time_field(prefix, type)
      @template.content_tag(:div, number_field(:"#{prefix}_#{type}s"), class: "#{type}_field") +
        @template.content_tag(:div, @template.content_tag(:span, "#{type[0]}", class: 'postfix'), class: "#{type}_suffix")
    end

    def hours_field(prefix)
      time_field prefix, :hour
    end

    def minutes_field(prefix)
      time_field prefix, :minute
    end

    def time_fields(prefix)
      @template.content_tag(:div,
                            hours_field(prefix) +
                            minutes_field(prefix),
                            class: "time_fields")
    end

    def flag_fields
      Meal::Flags.map do |desc, name|
        flag_field desc, name
      end.join.html_safe
    end

    def flag_field(desc, name)
      @template.content_tag(:label,
                            @template.check_box_tag("meal[flags][]",
                                                    name,
                                                    @object.flags.include?(name.to_s),
                                                    id: "meal_flags_#{name}") +
                            "\n" + desc)
    end

    def range_field(*args)
      super(*args) + @template.content_tag(:div, "", :class => 'rateit', 'data-rateit-backingfld' => "##{@object_name}_#{args.first}")
    end
  end

  def show_flags(meal)
    meal.flags.map(&:humanize).join(", ")
  end

  def meal_fields_for(record, *args, &block)
    options = args.extract_options!
    fields_for(record, *(args << options.merge(builder: MealsFormBuilder)), &block)
  end

  def meal_form_for(record, *args, &block)
    options = args.extract_options!
    form_for(record, *(args << options.merge(builder: MealsFormBuilder, as: :meal)), &block)
  end

  def no_results_message
    if params[:q]
      "Your search didn't match any of your meals."
    else
      "You haven't uploaded any meals!"
    end
  end
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
%head
  %title Meal Sorter

  %meta(charset="utf-8")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "vendor/custom.modernizr"
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
%body
  %header
    %h1
      = link_to "Meal Sorter", root_url
      %small A better way to use eMeals
    .spinner{style: 'display: none'}
    %hr

  = yield
</html>

app/views/meals/_dish.html.haml
= section type, class: 'hrecipe' do |s|
  - s.title class: 'fn' do
    = dish.name
  - s.content class: 'recipe-content' do
    %h4 Ingredients
    %ul
      - dish.ingredients.each do |ing|
        %li.ingredient
          %span.value= ing.amount
          - unless ing.unit.blank?
            %span.type= ing.unit
          = ing.description
    %h4 Instructions
    %ol.instructions
      - dish.instructions_list.each do |instruction|
        %li= instruction

app/views/meals/_dish_form.html.haml
= section type, class: type do |s|
  - s.title class: 'title' do
    = type.to_s.capitalize
  - s.content class: 'content' do
    = f.fields_for type do |dish|
      = dish.label :name, "#{type.to_s.capitalize} Name"
      = dish.text_field :name
      %label Ingredients
      .ingredients
        .ingredient_template
          = meal_fields_for "meal[#{type}_attributes][ingredients_attributes][$IDX$]", Ingredient.new do |ing|
            = render partial: 'ingredient_form', locals: {ing: ing, disabled: true}
        = dish.fields_for :ingredients do |ing|
          = render partial: 'ingredient_form', locals: {ing: ing, disabled: false}
      %button.add_ingredient.small.button Add Ingredient
      = dish.label :instructions, "Instructions"
      ~ dish.text_area :instructions

app/views/meals/_ingredient_form.html.haml
.ingredient
  = ing.hidden_field :_destroy, disabled: disabled
  .amount_field= ing.text_field :amount, disabled: disabled
  .unit_field= ing.unit_field :unit, disabled: disabled
  .description_field= ing.text_field :description, disabled: disabled
  .delete
    %a(href="#")
      %i.foundicon-minus

app/views/meals/edit.html.haml
%header#edit_meal_header
  %div
    %h2 Edit this Meal

%article#edit_meal
  = meal_form_for meal_form, url: meal_url(meal_form.meal), method: :put, html: {class: 'custom'} do |f|
    .row
      %aside.side_fields
        .row
          = f.label :rating, "Rating", class: 'inline column large-3'
          = f.range_field :rating, step: 1, min: 0, max: 5
        %fieldset
          %legend Flags
          = f.flag_fields
        %fieldset
          %legend Times
          = f.label :prep_time, "Prep Time"
          = f.time_fields :prep
          = f.label :cook_time, "Cook Time"
          = f.time_fields :cook
          = f.label :total_time, "Total Time"
          = f.time_fields :total
      %section.recipe_content
        %div{data: {section: 'auto'}}
          = render partial: 'dish_form', locals: {type: :entree, f: f}
          = render partial: 'dish_form', locals: {type: :side, f: f}

    .row
      .column.large-offset-3= f.submit "Save Meal Changes"

app/views/meals/index.html.haml
.row
  %section#meals
    .row
      .column.large-6
        %h2 Your Saved Meals
      = form_tag meals_url, method: :get, id: "search" do
        .column.large-4
          = text_field_tag :q, params[:q]
        .column.large-1
          %button.small Search
        .column.large-1
    - if meals.empty?
      %p= no_results_message
    - else
      %table#meals_list
        %thead
          %th Rating
          %th Entree
          %th Side Dish
          %th.options Options
        %tbody
          - meals.each do |meal|
            %tr
              %td
                .rateit{data: {rateit_value: meal.rating, rateit_readonly: "true"}}
              %td= link_to meal.entree.name, meal_url(meal)
              %td= link_to meal.side.name, meal_url(meal)
              %td.options
                %ul.button-group
                  %li= link_to icon(:edit), edit_meal_url(meal)
                  %li= link_to icon(:minus), hide_meal_url(meal), method: :delete
                  %li= link_to icon(:trash), meal_url(meal), method: :delete, data: {confirm: "Are you sure you want to delete this meal?"}
      = will_paginate meals

.row
  %section#upload_form
    %h3 Upload a Menu
    = form_tag upload_meals_url, multipart: true do
      = file_field_tag :menu
      = submit_tag "Upload"

app/views/meals/show.html.haml
%header#meal_header
  %div
    %h2= meal.entree.name
    %h3.subheader= meal.side.name

%section#meal_content
  %aside
    = form_tag rate_meal_url(meal), method: :patch, remote: true, class: 'rate_meal' do
      .message
      %label.inline.column.large-3(for="meal_rating") Rating
      %input#meal_rating{type: "range", name: "rating", step: "1", min: "0", max: "5", value: meal.rating}
      .autosubmit.rateit{data: {rateit_backingfld: "#meal_rating"}}
    - unless meal.flags.empty?
      .meal_flag= show_flags meal
    %ul.meal_times
      %li.total_time Total Time: #{meal.total_time}
      %li.prep_time Prep Time: #{meal.prep_time}
      %li.cook_time Cook Time: #{meal.cook_time}
  %article
    .recipe-container{data: {section: "tabs"}}
      = render partial: 'dish', locals: {dish: meal.entree, type: 'entree'}
      = render partial: 'dish', locals: {dish: meal.side, type: 'side'}